
package VentanaCliente;

import VentanaPrincipal.JFrame_Login;
import Clases.Cliente;
import Clases.Sistema;
import Frames.JPanel_Intro;
import Serializador.Serializador;
import Serializador.SerializadoraGen;
import java.awt.BorderLayout;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;

public class JFrame_Usuario extends javax.swing.JFrame {

    private Cliente c = Sistema.clienteActual;

    public JFrame_Usuario() {
        setUndecorated(true);
        initComponents();
        jLabelNombreBienvenida.setText(c.getNombres());
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Icono.png")).getImage());
        jButtonInicio.setIcon(setIcono("/Imagenes/Inicio.png", jButtonInicio));
        jButtonSalir.setIcon(setIcono("/Imagenes/Salir.png", jButtonSalir));
        jButtonPedido.setIcon(setIcono("/Imagenes/Mas.png", jButtonPedido));
        jButtonCarrito.setIcon(setIcono("/Imagenes/Carrito.png", jButtonCarrito));
//        jButtonTarjeta.setIcon(setIcono("/Imagenes/TarjetaC.png",jButtonCarrito));
    }

    //Métodos para íconos de los botones
    public Icon setIcono(String url, JButton button) {
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        int ancho = button.getWidth();
        int alto = button.getHeight();
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho - 20, alto - 20, Image.SCALE_DEFAULT));
        return icono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonSalir = new javax.swing.JButton();
        jButtonPedido = new javax.swing.JButton();
        jButtonCarrito = new javax.swing.JButton();
        jButtonInicio = new javax.swing.JButton();
        jButtonTarjeta = new javax.swing.JButton();
        JPanelIntro = new javax.swing.JPanel();
        jLabelNombreBienvenida = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setBackground(new java.awt.Color(102, 102, 255));
        jButtonSalir.setBorder(null);
        jButtonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 657, 50, 50));

        jButtonPedido.setBackground(new java.awt.Color(102, 102, 255));
        jButtonPedido.setBorder(null);
        jButtonPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPedidoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 69, 50, 50));

        jButtonCarrito.setBackground(new java.awt.Color(102, 102, 255));
        jButtonCarrito.setBorder(null);
        jButtonCarrito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCarritoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 137, 50, 50));

        jButtonInicio.setBackground(new java.awt.Color(102, 102, 255));
        jButtonInicio.setBorder(null);
        jButtonInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicioActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 50));

        jButtonTarjeta.setBackground(new java.awt.Color(102, 102, 255));
        jButtonTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/card_payment_50px.png"))); // NOI18N
        jButtonTarjeta.setBorder(null);
        jButtonTarjeta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTarjetaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 60, 50));

        JPanelIntro.setBackground(new java.awt.Color(255, 255, 255));

        jLabelNombreBienvenida.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 36)); // NOI18N
        jLabelNombreBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bienvenido,");

        javax.swing.GroupLayout JPanelIntroLayout = new javax.swing.GroupLayout(JPanelIntro);
        JPanelIntro.setLayout(JPanelIntroLayout);
        JPanelIntroLayout.setHorizontalGroup(
            JPanelIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelIntroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNombreBienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE))
                .addContainerGap())
        );
        JPanelIntroLayout.setVerticalGroup(
            JPanelIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelIntroLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabelNombreBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPanelIntro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JPanelIntro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed

        SerializadoraGen.serializarClientes("Clientes.txt", Sistema.cliente);
        SerializadoraGen.serializarMensajesClientes("ColaPedidos.txt", Sistema.colaPedidos);

        JFrame_Login VP = new JFrame_Login();
        VP.setLocationRelativeTo(null);
        VP.setVisible(true);
        this.dispose();
        VP.show();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPedidoActionPerformed
        // TODO add your handling code here:
        JPanel_Carrito PE = new JPanel_Carrito();
        PE.setSize(430, 695);//Tamaño del panel
        PE.setLocation(5, 5);//Posición dentro del panel principal

        JPanelIntro.removeAll();
        JPanelIntro.add(PE, BorderLayout.CENTER);
        JPanelIntro.revalidate();
        JPanelIntro.repaint();
    }//GEN-LAST:event_jButtonPedidoActionPerformed

    private void jButtonCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCarritoActionPerformed
        // TODO add your handling code here:
        JPanel_Pedido PC = new JPanel_Pedido();
        PC.setSize(430, 695);//Tamaño del panel
        PC.setLocation(5, 5);//Posición dentro del panel principal

        JPanelIntro.removeAll();
        JPanelIntro.add(PC, BorderLayout.CENTER);
        JPanelIntro.revalidate();
        JPanelIntro.repaint();
    }//GEN-LAST:event_jButtonCarritoActionPerformed

    private void jButtonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicioActionPerformed
        // TODO add your handling code here:
        JPanel_Intro PI = new JPanel_Intro();
        PI.setSize(424, 698);//Tamaño del panel
        PI.setLocation(5, 5);//Posición dentro del panel principal

        JPanelIntro.removeAll();
        JPanelIntro.add(PI, BorderLayout.CENTER);
        JPanelIntro.revalidate();
        JPanelIntro.repaint();
    }//GEN-LAST:event_jButtonInicioActionPerformed

    private void jButtonTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTarjetaActionPerformed
        // TODO add your handling code here:
        VincularTarjeta v = new VincularTarjeta();
        v.setSize(424, 698);//Tamaño del panel
        v.setLocation(5, 5);//Posición dentro del panel principal

        JPanelIntro.removeAll();
        JPanelIntro.add(v, BorderLayout.CENTER);
        JPanelIntro.revalidate();
        JPanelIntro.repaint();
    }//GEN-LAST:event_jButtonTarjetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelIntro;
    private javax.swing.JButton jButtonCarrito;
    private javax.swing.JButton jButtonInicio;
    private javax.swing.JButton jButtonPedido;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonTarjeta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelNombreBienvenida;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
